# Generated by Django 4.2.11 on 2026-05-11 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('product_images', 'Product Image'), ('invoice_pdfs', 'Invoice PDF'), ('avatars', 'Avatar'), ('documents', 'Document')], max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=2000)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'file_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
